version: '3'
services:
  lastredux:
    container_name: 'reactdockertwo'
    image: 'reactdockertwo'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /:/src/index